Client[webapi_consumer]/Controllers/AllChildrenController.cs
using CompanyStructured.Common.Models;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Client_webapi_consumer_.Controllers
{
    public class AllChildrenController : Controller
    {
        // GET: AllChildren

        public ActionResult Index()
        {
            List<Node> nodes = new List<Node>();
            return View(nodes);
        }
        [HttpPost]
        public async Task<ActionResult> Index(string txtnodeid)
        {
      
            List<Node> nodes = new List<Node>();

            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(Share.Baseurl);

                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllchildren using HttpClient  
                HttpResponseMessage Res = await client.GetAsync($"api/Hierarchy/{txtnodeid}");
                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var Response = Res.Content.ReadAsStringAsync().Result;

                    //Deserializing the response recieved from web api and storing into the Node list  

                    nodes = new JavaScriptSerializer().Deserialize<List<Node>>(Response);
                }
                //returning the node list to view  
                return View(nodes);
            }
        }
    }
}

Client[webapi_consumer]/Controllers/Change_Current_Parent_Controller.cs
using CompanyStructured.Common.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Net.Http.Formatting;
using System.Web.Configuration;

namespace Client_webapi_consumer_.Controllers
{
    public class Change_Current_Parent_Controller : Controller
    {
        // GET: Change_Current_Parent_

        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task Index(int id, int newParentId)
        {
            parentchange pc = new parentchange { id = id, newparentid = newParentId };

            using (var client = new HttpClient())
            {
                // Update port # in the following line.
                client.BaseAddress = new Uri(Share.Baseurl);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(
                    new MediaTypeWithQualityHeaderValue("application/json"));

                StringContent content = new StringContent(JsonConvert.SerializeObject(pc), Encoding.UTF8, "application/json");

                HttpResponseMessage response = await client.PostAsync(
        "api/ChangeParent", content);

                if (response.IsSuccessStatusCode)
                     Response.Write($"Succeed action!" + response.StatusCode);
                else
                    response.EnsureSuccessStatusCode();
            }
        }
    }
}

Client[webapi_consumer]/Controllers/HeightController.cs
using CompanyStructured.Common.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace Client_webapi_consumer_.Controllers
{
    public class HeightController : Controller
    {
        // GET: Height
   
        int height = 0;

        public ActionResult Index()
        {
            ViewBag.Baseurl = Share.Baseurl;
            return View();
        }
        public async Task<int> getheight(int id)
        {
           
            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(Share.Baseurl);

                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json")); 
                HttpResponseMessage Res = await client.GetAsync($"api/Height/{id}");
 
                if (Res.IsSuccessStatusCode)
                {
                     
                    var Response = Res.Content.ReadAsStringAsync().Result;
 

                    height = new System.Web.Script.Serialization.JavaScriptSerializer().Deserialize<int>(Response);
                }
                //returning the node list to view  
                return height;
            }
        }
 
    }
}

Client[webapi_consumer]/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Client_webapi_consumer_.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Client[webapi_consumer]/Controllers/RootController.cs
using CompanyStructured.Common.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Client_webapi_consumer_.Controllers
{
    public class RootController : Controller
    {
        // GET: Root
        
        public async Task<ActionResult> Index()
        {
            Node root = new Node();
            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(Share.Baseurl);

                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllchildren using HttpClient  
                HttpResponseMessage Res = await client.GetAsync($"api/Root");
                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var Response = Res.Content.ReadAsStringAsync().Result;

                    //Deserializing the response recieved from web api and storing into the Node list  

                     root = new JavaScriptSerializer().Deserialize<Node>(Response);
                }
                //returning the node list to view  
                return View(root);
            }

        }
    }
}

Client[webapi_consumer]/Views/AllChildren/Index.cshtml
@model IEnumerable<CompanyStructured.Common.Models.Node>

@{
    ViewBag.Title = "Show all sttuffs";
}

<h2>All children</h2>

@using (Html.BeginForm("Index", "AllChildren", FormMethod.Post))
{
    <div class="form-horizontal">
        <hr />
        <div class="form-group">

            <div class="col-md-10">
                <input name="txtnodeid" type="text" />

            </div>
        </div>


        <input id="btn" onclick="Getrequest()" type="submit" value="get all decsendants" class="btn btn-default" />
    </div>

    @Html.ActionLink("Back", "Index", "Home")
    <table id="tblEmployee" class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
            </tr>
        }

    </table>
}
<script type="text/javascript">
    function Getrequest() {
        @ViewBag.id=  $('#txtnodeid').val()
    }
</script>
@*<script type="text/javascript">

    function Getrequest() {
        $.get('@Url.Action("Index", "AllChildren")', { id: $('#txtnodeid').val() }, function (data) {
            var tblEmployee = $("#tblEmployee");
            $.each(data, function (index, item) {
                var tr = $("<tr></tr>");
                tr.html(("<td>" + item.Id + "</td>")
               // tblEmployee.append(tr);
                    alert(tr);

            });
        });
    }
    </script>*@

@*<script>
        function Getrequest() {
            $.ajax({
                url: '@Url.Action("Index", "AllChildren")',
                type: 'Get',
                data: { id: $('#txtnodeid').val() },
                dataType: 'json',
                success: function (data) {
                    alert(data)
                }
            });
        }
    </script>*@

Client[webapi_consumer]/Views/Change_Current_Parent_/Index.cshtml
@model CompanyStructured.Common.Models.NewParent

@{
    ViewBag.Title = "View";
}

<h2>Change parent</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Node</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.newParentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.newParentId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.newParentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Change Parent" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@Html.ActionLink("Back", "Index", "Home")

@*<div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>*@

Client[webapi_consumer]/Views/Height/Index.cshtml
@{
    ViewBag.Title = "get height";
}

<h2>height of given node is:</h2>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<div class="form-horizontal">
    <hr />
    <div class="form-group">

        <div class="col-md-10">
            <input id="txtnodeid" type="text" value="" />

        </div>
    </div>
    <p id="result">

    </p>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input id="btnSubmit" type="submit" onclick="Getrequest()" value="get height of the node" class="btn btn-default" />
        </div>
    </div>
</div>

@Html.ActionLink("Back", "Index", "Home")

<script>
    function Getrequest() {
        $.ajax({
            url: '@Url.Action("getheight", "Height")',
            type: 'Get',
            data: { id: $('#txtnodeid').val() },
            dataType: 'json',
            success: function (data) {
                $('#result').text( 'Height of the node is :' + data);
            }
        });
    }
</script>

Client[webapi_consumer]/Views/Home/Index.cshtml
@{
    ViewBag.Title = "";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Get descendants of given node", "Index" , "AllChildren" ,null , null)
</p>
<p>
    @Html.ActionLink("Change Parent", "Index", "Change_Current_Parent_", null, null)
</p>
<p>
    @Html.ActionLink("Get height of the given node", "Index", "Height", null, null)
</p>
<p>
    @Html.ActionLink("Get Root of tree", "Index", "root", null, null)
</p>

Client[webapi_consumer]/Views/Root/Index.cshtml
@model CompanyStructured.Common.Models.Node

@{
    ViewBag.Title = "get root";
}

<h2>Root is:</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

    </dl>
</div>
@Html.ActionLink("Back", "Index", "Home")

Client[webapi_consumer]/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Company tree Structure", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - By Mehdi Bayat</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>